import { readFileSync } from 'node:fs';

import {
  createPublicClient,
  createWalletClient,
  decodeEventLog,
  getAddress,
  http,
  type Abi,
  type PublicClient,
  type WalletClient,
} from 'viem';
import { privateKeyToAccount } from 'viem/accounts';

import { hederaTestnet } from './chain';

export type VaultStatus = 'Active' | 'Frozen' | 'Closed';

const STATUS_NAMES: Readonly<Record<number, VaultStatus>> = Object.freeze({
  0: 'Active',
  1: 'Frozen',
  2: 'Closed',
});

const REJECT_REASON_NAMES: Readonly<Record<number, string>> = Object.freeze({
  0: 'InvalidAmount',
  1: 'NotActive',
  2: 'Expired',
  3: 'RecipientNotAllowed',
  4: 'BudgetExceeded',
  5: 'InsufficientPrincipal',
  6: 'TransferFailed',
});

export interface VaultAction {
  /** bytes32 action/evidence id. */
  readonly evidenceId: `0x${string}`;
  readonly recipient: `0x${string}`;
  /** Amount in tinybar. */
  readonly amount: bigint;
}

export interface VaultState {
  readonly status: VaultStatus;
  /** Budget cap in tinybar, serialized as a decimal string. */
  readonly budgetCapTinybar: string;
  /** Mandate deadline as a unix seconds string. */
  readonly deadlineUnixSeconds: string;
  readonly spentTinybar: string;
  readonly principalBalanceTinybar: string;
  readonly stakeBalanceTinybar: string;
}

export type VaultActionEvent =
  | {
      readonly kind: 'ActionExecuted';
      readonly evidenceId: string;
      readonly recipient: string;
      readonly amountTinybar: string;
      readonly txHash: string;
      readonly blockNumber: bigint;
      readonly logIndex: number;
    }
  | {
      readonly kind: 'ActionRejected';
      readonly evidenceId: string;
      readonly rejectReason: string;
      readonly txHash: string;
      readonly blockNumber: bigint;
      readonly logIndex: number;
    };

export class HederaVaultError extends Error {
  constructor(
    readonly code:
      | 'ABI_MISSING'
      | 'INVALID_ADDRESS'
      | 'INVALID_PRIVATE_KEY'
      | 'UNEXPECTED_CHAIN'
      | 'EXECUTION_FAILED',
  ) {
    super(`Hedera vault adapter failed (${code})`);
    this.name = 'HederaVaultError';
  }
}

let cachedAbi: Abi | undefined;

/** The ABI is generated by Hardhat; never maintained by hand. */
export function loadVaultAbi(): Abi {
  if (cachedAbi !== undefined) return cachedAbi;
  try {
    const artifact = JSON.parse(
      readFileSync('artifacts/contracts/PolicyVault.sol/PolicyVault.json', 'utf8'),
    ) as { abi?: unknown };
    if (!Array.isArray(artifact.abi) || artifact.abi.length === 0) {
      throw new Error('empty abi');
    }
    cachedAbi = artifact.abi as Abi;
    return cachedAbi;
  } catch {
    throw new HederaVaultError('ABI_MISSING');
  }
}

function requireAddress(value: string, code: 'INVALID_ADDRESS'): `0x${string}` {
  try {
    return getAddress(value);
  } catch {
    throw new HederaVaultError(code);
  }
}

export function createVaultPublicClient(rpcUrl: string): PublicClient {
  return createPublicClient({ chain: hederaTestnet, transport: http(rpcUrl) });
}

export async function isRecipientAllowed(
  publicClient: PublicClient,
  vaultAddress: string,
  recipient: string,
): Promise<boolean> {
  const address = requireAddress(vaultAddress, 'INVALID_ADDRESS');
  const recipientAddress = requireAddress(recipient, 'INVALID_ADDRESS');
  const abi = loadVaultAbi();
  const allowed = await publicClient.readContract({
    address,
    abi,
    functionName: 'isRecipientAllowed',
    args: [recipientAddress],
  });
  return allowed as boolean;
}

export async function readVaultState(
  publicClient: PublicClient,
  vaultAddress: string,
): Promise<VaultState> {
  const address = requireAddress(vaultAddress, 'INVALID_ADDRESS');
  const abi = loadVaultAbi();

  const [mandate, status, spent, principalBalance, stakeBalance] = await Promise.all([
    publicClient.readContract({ address, abi, functionName: 'mandate' }),
    publicClient.readContract({ address, abi, functionName: 'status' }),
    publicClient.readContract({ address, abi, functionName: 'spent' }),
    publicClient.readContract({ address, abi, functionName: 'principalBalance' }),
    publicClient.readContract({ address, abi, functionName: 'stakeBalance' }),
  ]);

  const mandateTuple = mandate as readonly [string, bigint, bigint];
  const statusName = STATUS_NAMES[Number(status)];

  return {
    status: statusName ?? 'Active',
    budgetCapTinybar: mandateTuple[1].toString(),
    deadlineUnixSeconds: mandateTuple[2].toString(),
    spentTinybar: (spent as bigint).toString(),
    principalBalanceTinybar: (principalBalance as bigint).toString(),
    stakeBalanceTinybar: (stakeBalance as bigint).toString(),
  };
}

export function decodeVaultLog(
  log: { topics: readonly `0x${string}`[]; data: `0x${string}`; blockNumber?: bigint },
  txHash: string,
  logIndex: number,
): VaultActionEvent | undefined {
  if (log.topics.length === 0) return undefined;
  const decoded = decodeEventLog({
    abi: loadVaultAbi(),
    data: log.data,
    topics: [log.topics[0] as `0x${string}`, ...log.topics.slice(1)],
  });
  const blockNumber = log.blockNumber ?? 0n;
  if (decoded.eventName === 'ActionExecuted') {
    const args = decoded.args as unknown as {
      evidenceId: string;
      recipient: string;
      amount: bigint;
    };
    return {
      kind: 'ActionExecuted',
      evidenceId: args.evidenceId,
      recipient: getAddress(args.recipient),
      amountTinybar: args.amount.toString(),
      txHash,
      blockNumber,
      logIndex,
    };
  }
  if (decoded.eventName === 'ActionRejected') {
    const args = decoded.args as unknown as { evidenceId: string; reason: number };
    return {
      kind: 'ActionRejected',
      evidenceId: args.evidenceId,
      rejectReason: REJECT_REASON_NAMES[Number(args.reason)] ?? `Unknown(${Number(args.reason)})`,
      txHash,
      blockNumber,
      logIndex,
    };
  }
  return undefined;
}

/**
 * Hedera's public JSON-RPC relay rejects an eth_getLogs range whose block
 * timestamps span more than 7 days (error -32004), so the scan is split into
 * bounded windows. 50k blocks is ~1 day at Hedera's ~2s block time — well
 * inside the cap even if the chain ever sped up.
 */
const MAX_BLOCKS_PER_LOG_QUERY = 50_000n;

export async function readVaultActions(
  publicClient: PublicClient,
  vaultAddress: string,
  options: { fromBlock: bigint; toBlock?: bigint },
): Promise<readonly VaultActionEvent[]> {
  const address = requireAddress(vaultAddress, 'INVALID_ADDRESS');
  const abi = loadVaultAbi();
  const toBlock = options.toBlock ?? (await publicClient.getBlockNumber());

  const events: VaultActionEvent[] = [];
  for (let start = options.fromBlock; start <= toBlock; start += MAX_BLOCKS_PER_LOG_QUERY) {
    const windowEnd = start + MAX_BLOCKS_PER_LOG_QUERY - 1n;
    const end = windowEnd < toBlock ? windowEnd : toBlock;

    const [executedLogs, rejectedLogs] = await Promise.all([
      publicClient.getContractEvents({
        address,
        abi,
        eventName: 'ActionExecuted',
        fromBlock: start,
        toBlock: end,
      }),
      publicClient.getContractEvents({
        address,
        abi,
        eventName: 'ActionRejected',
        fromBlock: start,
        toBlock: end,
      }),
    ]);

    for (const log of [...executedLogs, ...rejectedLogs]) {
      const decoded = decodeVaultLog(
        { topics: log.topics, data: log.data, blockNumber: log.blockNumber },
        log.transactionHash ?? '',
        log.logIndex ?? 0,
      );
      if (decoded !== undefined) events.push(decoded);
    }
  }
  return events;
}

export interface VaultExecutionResult {
  readonly txHash: string;
  readonly executed: boolean;
  readonly rejectionReason?: string;
}

/**
 * Agent-side execution. The agent signer has no owner/verifier rights, so the
 * only meaningful call here is `execute`; rejections come back as events, not
 * reverts.
 */
export async function executeVaultAction(
  config: { rpcUrl: string; vaultAddress: string; agentPrivateKey: string },
  action: VaultAction,
): Promise<VaultExecutionResult> {
  const vaultAddress = requireAddress(config.vaultAddress, 'INVALID_ADDRESS');
  if (!/^0x[0-9a-fA-F]{64}$/.test(config.agentPrivateKey)) {
    throw new HederaVaultError('INVALID_PRIVATE_KEY');
  }
  const abi = loadVaultAbi();

  let account;
  try {
    account = privateKeyToAccount(config.agentPrivateKey as `0x${string}`);
  } catch {
    throw new HederaVaultError('INVALID_PRIVATE_KEY');
  }
  const wallet: WalletClient = createWalletClient({
    account,
    chain: hederaTestnet,
    transport: http(config.rpcUrl),
  });

  const publicClient = createVaultPublicClient(config.rpcUrl);
  const hash = await wallet.writeContract({
    address: vaultAddress,
    abi,
    functionName: 'execute' as const,
    args: [action] as never as readonly unknown[],
    account,
    chain: hederaTestnet,
  });

  const receipt = await publicClient.waitForTransactionReceipt({ hash });
  if (receipt.status !== 'success') {
    throw new HederaVaultError('EXECUTION_FAILED');
  }

  const events: VaultActionEvent[] = [];
  for (const log of receipt.logs) {
    const decoded = decodeVaultLog(
      { topics: log.topics, data: log.data },
      log.transactionHash ?? hash,
      log.logIndex ?? 0,
    );
    if (decoded !== undefined) events.push(decoded);
  }

  const executed = events.find((event) => event.kind === 'ActionExecuted');
  const rejected = events.find((event) => event.kind === 'ActionRejected');
  return {
    txHash: hash,
    executed: executed !== undefined,
    ...(rejected !== undefined && executed === undefined
      ? { rejectionReason: rejected.rejectReason }
      : {}),
  };
}
